# Doom Tomorrow Day status content for tmux
# Based on nordtheme/tmux structure

#+----------------+
#+ Plugin Support +
#+----------------+
#+--- tmux-prefix-highlight ---+
set -g @prefix_highlight_output_prefix "#[fg=#4271ae]#[bg=#ffffff]#[nobold]#[noitalics]#[nounderscore]#[bg=#4271ae]#[fg=#ffffff]"
set -g @prefix_highlight_output_suffix ""
set -g @prefix_highlight_copy_mode_attr "fg=#4271ae,bg=#ffffff,bold"

#+--------+
#+ Status +
#+--------+
#+--- Bars ---+
set -g status-left "#[fg=#ffffff,bg=#4271ae,bold] #S #[fg=#4271ae,bg=#ffffff,nobold,noitalics,nounderscore]"
set -g status-right "#{prefix_highlight}#[fg=#e4e4e4,bg=#ffffff,nobold,noitalics,nounderscore]#[fg=#4d4d4c,bg=#e4e4e4] %Y-%m-%d #[fg=#4d4d4c,bg=#e4e4e4,nobold,noitalics,nounderscore]#[fg=#4d4d4c,bg=#e4e4e4] %H:%M #[fg=#3e999f,bg=#e4e4e4,nobold,noitalics,nounderscore]#[fg=#ffffff,bg=#3e999f,bold] #H "

#+--- Windows ---+
set -g window-status-format "#[fg=#ffffff,bg=#e4e4e4,nobold,noitalics,nounderscore] #[fg=#4d4d4c,bg=#e4e4e4]#I #[fg=#4d4d4c,bg=#e4e4e4,nobold,noitalics,nounderscore] #[fg=#4d4d4c,bg=#e4e4e4]#W #F #[fg=#e4e4e4,bg=#ffffff,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=#ffffff,bg=#3e999f,nobold,noitalics,nounderscore] #[fg=#ffffff,bg=#3e999f]#I #[fg=#ffffff,bg=#3e999f,nobold,noitalics,nounderscore] #[fg=#ffffff,bg=#3e999f]#W #F #[fg=#3e999f,bg=#ffffff,nobold,noitalics,nounderscore]"
set -g window-status-separator ""
